version: '2'
services:
  nginx:
    image: pagespeed/nginx-pagespeed:latest
    container_name: dx-next-nginx-dev
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "./nginx/conf.d:/etc/nginx/conf.d"
    links:
    - express

  express:
    image: node:alpine
    container_name: dx-next-express-dev
    hostname: express
    volumes:
    - ".:/src:cached"
    working_dir: /src
    command: [sh, -c, npm install && npm run build && npm run start]
    ports:
    - "3000:3000"
