version: '2'
services:
  express:
    container_name: dx-next-express-dev
    build:
      context: ../../../
      dockerfile: ./docker/development/express/Dockerfile
      args:
        APP_ROOT: /var/www
        FILES: /src
    volumes:
      - '../../../.:/src'
      - '../../../mounts/lsyncd/conf.d:/etc/lsyncd/conf.d'
    command:
      [
        sh,
        -c,
        rsync -av --exclude 'node_modules' --exclude 'docker' --exclude 'mounts' /src/ /var/www && cd /var/www && rsync --daemon && mkdir -p /var/log/lsyncd && touch /var/log/lsyncd/lsyncd.log && lsyncd /etc/lsyncd/conf.d/default.conf && yarn upgrade && yarn build && yarn start,
      ]
    ports:
      - '3000:3000'
    env_file: ../../../.env
  nginx:
    links:
      - express
