version: '2'
services:
  express:
    container_name: dx-next-express-dev
    build:
      context: ../../../
      dockerfile: ./docker/development/express/Dockerfile
      args:
        APP_ROOT: /var/www
        FILES: /src
    volumes:
      - '../../../.:/src:cached'
    command:
      [
        sh,
        -c,
        rsync -av --exclude 'node_modules' /src/ /var/www && yarn upgrade && yarn build && yarn start,
      ]
    ports:
      - '3000:3000'
    env_file: ../../../.env
  nginx:
    links:
      - express
